version: 2
updates:
  - package-ecosystem: npm
    directory: /.github/actions/get-latest-npm-branch-version
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /.github/docker/centreon-web/alma8
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /.github/docker/centreon-web/alma9
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /.github/docker/centreon-web/bullseye
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /.github/docker/keycloak
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/lighthouse
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/packages/js-config
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/packages/ui-context
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/packages/ui
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/tests/e2e
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/tests/rest_api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /centreon/www/widgets
    schedule:
      interval: daily
