name: chromatic-nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1,2,3,4"

env:
  directory: "centreon/packages/ui"

jobs:
  publish-snapshots:
    if: ${{ github.event_name == 'schedule' && github.ref_name == 'develop' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/chromatic
        with:
          frontend_directory: ${{ env.directory }}
          dependencies_lock_file: centreon/pnpm-lock.yaml
          pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          project_token: ${{ secrets.CHROMATIC_TOKEN }}
