---
name: Create awie jira version

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon-awie/**"
  workflow_dispatch:

env:
  module: "awie"

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          module_name: ${{ env.module }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
