# test branch names

on:
  workflow_call:

jobs:
  names:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: DEBUG - Github head ref
        run: echo ${{ github.head_ref }} #TODO: to remove

      - name: DEBUG - Github ref Name
        run: echo ${{ github.ref_name }} #TODO: to remove

      - name: DEBUG - Github base ref
        run: echo ${{ github.base_ref }} #TODO: to remove

      - name: DEBUG - Github run_id
        run: echo ${{ github.run_id }} #TODO: to remove

      - name: DEBUG - Hello world
        run: echo Hello world from $GITHUB_BASE_REF #TODO: to remove

      - name: Get current time
        run: echo "$(date +'%Y-%m-%d %H:%M:%S')"