name: Launch Veracode pipeline scan

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

env:
  ZIP_NAME: "${{ github.event.pull_request.base.repo.name }}-${{ github.event.pull_request.number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: debug - Check location
        run: ls -la

      - name: debug - Zip name
        run: echo "${{ env.ZIP_NAME }}"

      - name: Create zip file
        run: zip -r ${{ env.ZIP_NAME }} *

      - name: debug - Check location
        run: ls -la

      - name: Create zip file
        run: mv ${{ env.ZIP_NAME }}.zip poc_target

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}.zip
          path: ${{ env.ZIP_NAME }}.zip

  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: pipeline scan
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}.zip

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.4
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: ${{ env.ZIP_NAME }}.zip
          request_policy: "test POV"
          fail_build: true
          debug: 1
          verbose: true
